# Numpy library


Core library for scientific computing in Python. It provides a
high-performance multidimensional array object, and tools for
working with these arrays
1. Numeric Python
2. Calculation over entire arrays
3. Efficient
4. Linear algebra

BE AWARE:
- can only contain values of the same type!
- operator + works differently than with LIST type!

In [1]:
import numpy as np

scores = [24, 23, 30, 29, 17, 16, 15]

np_scores = np.array(scores)

print(np_scores)  #or try *2 or whatever operation...

print(scores*2)
print(np_scores*2)

#print(np_scores) 
print(np_scores+1)  

print(type(scores))
print(type(np_scores))

[24 23 30 29 17 16 15]
[24, 23, 30, 29, 17, 16, 15, 24, 23, 30, 29, 17, 16, 15]
[48 46 60 58 34 32 30]
[25 24 31 30 18 17 16]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
#subsetting as the list type using square brackets
np_scores[3:-2]
# we can convert it to a list
#np_scores_list=np_scores.tolist()
#np_scores_list[:4]

array([29, 17])

In [2]:
## subsetting specifically for numpy 
np_scores >= 18

array([ True,  True,  True,  True, False, False, False])

In [3]:
np_scores[np_scores>=18]

array([24, 23, 30, 29])

# 2D Numpy arrays

In [ ]:
scores_1 = [24, 23, 30, 29, 17, 16, 15]
scores_2 = [15, 26, 24, 25, 18, 30, 23]

In [ ]:
np_2d_scores = np.array([scores_1,scores_2])

In [ ]:
np_2d_scores  #as a list of lists 

In [ ]:
np_2d_scores.shape  

In [ ]:
np_2d_scores[0][2]
np_2d_scores[0,2]

In [ ]:
np_2d_scores[:,1:3] #all rows

In [ ]:
np_2d_scores[1,:] #all columns first row

## Loop on a numpy array

In [ ]:
for score in scores: 
    print(score)

In [ ]:
for score in np_2d_scores: #doesnt work if 2D
    print(score)


In [ ]:
for val in np.nditer(np_2d_scores):
    print(val) 

In [ ]:
for row in np_2d_scores:
    for x in row:
        print(x)

## We can go  further

In [ ]:
np_2d_scores_2 = np_2d_scores*2
np_2d_scores_2 

In [ ]:
np_3d_scores=[np_2d_scores,np_2d_scores_2]  

In [ ]:
np_3d_scores

In [ ]:
np.shape(np_3d_scores)

In [ ]:
np_3d_scores[0][1][3]
np_3d_scores[1][:,1]

## Try by yourself

- Create a random array of length 100.Hint: np.random.rand()
- Sort your array.
- Compute the mean, median and sample variance.